version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongodb:/data/db:Z,U
