// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BurnItClient is the client API for BurnIt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BurnItClient interface {
	// Sums two integers.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
}

type burnItClient struct {
	cc grpc.ClientConnInterface
}

func NewBurnItClient(cc grpc.ClientConnInterface) BurnItClient {
	return &burnItClient{cc}
}

func (c *burnItClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, "/pb.BurnIt/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BurnItServer is the server API for BurnIt service.
// All implementations must embed UnimplementedBurnItServer
// for forward compatibility
type BurnItServer interface {
	// Sums two integers.
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	mustEmbedUnimplementedBurnItServer()
}

// UnimplementedBurnItServer must be embedded to have forward compatible implementations.
type UnimplementedBurnItServer struct {
}

func (UnimplementedBurnItServer) Create(context.Context, *CreateRequest) (*CreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBurnItServer) mustEmbedUnimplementedBurnItServer() {}

// UnsafeBurnItServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BurnItServer will
// result in compilation errors.
type UnsafeBurnItServer interface {
	mustEmbedUnimplementedBurnItServer()
}

func RegisterBurnItServer(s grpc.ServiceRegistrar, srv BurnItServer) {
	s.RegisterService(&BurnIt_ServiceDesc, srv)
}

func _BurnIt_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnItServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BurnIt/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnItServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BurnIt_ServiceDesc is the grpc.ServiceDesc for BurnIt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BurnIt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BurnIt",
	HandlerType: (*BurnItServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BurnIt_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
